smuproj/apps/articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment,
         name='leave_comment')
]

smuproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('articles/', include(('articles.urls', 'articles'),
                              namespace='articles')),
    path('admin/', admin.site.urls)
]

smuproj/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.


class Article(models.Model):
    article_title = models.CharField('название статьи',
                                     max_length=250)
    article_text = models.TextField('текст статьи')
    pub = models.DateTimeField('дата публикации')
    
    def __str__(self):
        return self.article_title
    
    def was_published_recently(self):
        return self.pub >= (timezone.now() - datetime.timedelta(days=7))
    
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора',
                                   max_length=75)
    comment_text = models.CharField('текст комментария',
                                    max_length=500)
    
    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
    

smuproj/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
# from django.http import HttpResponse
from .models import Article


# def index(request):
#     return HttpResponse("Йа йа, май Фюрер!")
#
#
# def test(request):
#     return HttpResponse('ВЫПЬЕМ ВОДЫ БАЙКАЛЬСКОЙ, БРАТЬЯ РУСЫ!!!')

# название приложения (для однозначного указания псевдонимов url)
app_name = 'articles'


def index(request):
    latest_articles_list = Article.objects.order_by('-pub')[:5]
    return render(request, 'articles/list.html',
                  {'latest_articles_list': latest_articles_list})

 
def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Статья не найдена. МОХ')
    
    latest_comm_list = a.comment_set.order_by('id')[:10]
    return render(request, 'articles/detail.html',
                  {
                      'article': a,
                      'latest_comm_list': latest_comm_list
                  })
 
 
def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Статья не найдена. МОХ МОХ')
    
    a.comment_set.create(author_name=request.POST['inname'],
                         comment_text=request.POST['incommenttext'])
    return HttpResponseRedirect(
        reverse('articles:detail', args=(a.id,)))

smuproj/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}{{article.article_title}}{% endblock %}
{% block content %}
    <h2 style="text-align: center;">{{article.article_title}}</h2>
    <p style="text-align: center;">{{article.article_text}}</p>
    <em style="padding-left: 15em">{{article.pub}}</em>
    <br>
    <br>
    {% if article.was_published_recently %}
        <strong style="color: red; font-size: 1.2em; padding-left: 12.5em;">НОВАЯ СТАТЬЯ</strong>
    {% endif %}
    <br>
    <br>
    <hr>
    <br>
    {% if latest_comm_list %}
        {% for c in latest_comm_list %}
            <p style="margin: 20px auto;">
                <strong>{{c.author_name}}</strong>
                <br>
                {{c.comment_text}}
                <br>
            </p>
        {% endfor %}
        {% else %}
            Комментарии не найдены. Оставьте его первым!
    {% endif %}
    <br>
    <hr>
    <br>
    <form action="{% url 'articles:leave_comment' article.id %}" method="POST">
        {% csrf_token %}
        <input type="text" required placeholder="Ваше имя" name="inname">
        <br>
        <textarea name="incommenttext" required placeholder="Текст комментария" cols="30" rows="10"></textarea>
        <br>
        <button type="submit">Оставить комментарий (и душу)</button>
    </form>
{% endblock %}

smuproj/templates/articles/list.html
{% extends 'base.html' %}
{% block title %}Последние статьи{% endblock %}
{% block content %}
    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
            <br>
        {% endfor %}
    {% else %}
        Статьи не найдены. Найдите и больше не теряйте.
    {% endif %}
{% endblock %}

smuproj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Самый правдивый сайт про нашу историю{% endblock %}</title>
</head>
<body style="width: 1000px; margin: auto;">
    {% block content %}Ага, ага. А чему оно равно, блять!?{% endblock %}
</body>
</html>